Repository systopia/de.systopia.contract, pull requests merged in 2025-06, with the labels that each got.

#89 Add tests for contract forms
  .github/workflows/phpstan.yml
  .github/workflows/phpunit.yml
  CRM/Contract/BAO/ContractPaymentLink.php
  CRM/Contract/Change.php
  CRM/Contract/Change/Cancel.php
  CRM/Contract/Change/Pause.php
  CRM/Contract/Change/Resume.php
  CRM/Contract/Change/Sign.php
  CRM/Contract/Change/Upgrade.php
  CRM/Contract/Form/Create.php
  CRM/Contract/Form/Modify.php
  CRM/Contract/SepaLogic.php
  CRM/Contract/Utils.php
  Civi/Contract/ActionProvider/Action/CancelContract.php
  Civi/Contract/ActionProvider/Action/CreateContract.php
  Civi/Contract/ActionProvider/Action/GetContract.php
  api/v3/Contract/Create.php
  ci/composer.json
  info.xml
  phpstan.ci.neon
  phpstan.neon.dist
  phpstan.neon.template
  tests/phpunit/CRM/Contract/ContractTestBase.php
  tests/phpunit/CRM/Contract/CustomisationTest.php
  tests/phpunit/CRM/Contract/EngineStressTest.php
  tests/phpunit/CRM/Contract/Form/CreateFormTest.php
  tests/phpunit/CRM/Contract/Form/ModifyFormTest.php
  tests/phpunit/CRM/Contract/UtilsTest.php
Labels: enhancement, status:needs work

#91 Coverage for no payment required
  CRM/Contract/Change.php
  CRM/Contract/Configuration.php
  CRM/Contract/Form/Create.php
  CRM/Contract/Form/Modify.php
  CRM/Contract/FormUtils.php
  CRM/Contract/RecurringContribution.php
  CRM/Contract/SepaLogic.php
  CRM/Contract/Upgrader.php
  contract.php
  js/contract_modify_tools.js
  js/hide-ce-activity-types.js
  js/sepa_tools.js
  templates/CRM/Contract/Form/Modify.tpl
  templates/CRM/Member/Form/Membership.js
  templates/CRM/Member/Page/Tab.js
  tests/phpunit/CRM/Contract/Form/CreateFormTest.php
  tests/phpunit/CRM/Contract/Form/ModifyFormTest.php
Labels: bug, enhancement, status:reviewed and tested

#92 Use Ajax snippet 2 for not printing when loading contract details in membership table
  templates/CRM/Member/Page/Tab.js
Labels: bug, status:needs review
