Repository systopia/de.systopia.contract, pull requests merged in 2025-08, with the labels that each got.

#109 Consolidate JavaScript files
  CRM/Contract/Form/Create.php
  CRM/Contract/SepaLogic.php
  js/contract_modify_tools.js
  js/sepa_tools.js
Labels: status:reviewed and tested

#110 Use correct name for "no payment required" payment method
  CRM/Contract/Upgrader.php
Labels: status:reviewed and tested

#111 Update contact summary tabs after creating/modifying contracts
  CRM/Contract/Form/Create.php
  CRM/Contract/Form/Modify.php
  CRM/Contract/FormUtils.php
Labels: status:reviewed and tested

#113 Allow passing activity's date/time in `Contract.create` API
  api/v3/Contract/Create.php
Labels: enhancement, status:needs review

#114 test(ModifyForm): resolve payment_instrument_id by name
  CRM/Contract/Upgrader.php
  tests/phpunit/CRM/Contract/Form/CreateFormTest.php
  tests/phpunit/CRM/Contract/Form/ModifyFormTest.php
Labels: bug, status:needs review
