Repository systopia/de.systopia.contract, pull requests merged in 2025-07, with the labels that each got.

#96 Remove confusing "contract" from payment options
  CRM/Contract/Configuration.php
Labels: enhancement, status:needs review

#97 Correctly record recurring contribution ID for new contracts with SEPA mandate
  CRM/Contract/Form/Create.php
Labels: bug, status:needs review

#94 Fix create/modify forms: remove fundraiser field and adjust installment preview
  CRM/Contract/Form/Create.php
  js/contract_modify_tools.js
  templates/CRM/Contract/Form/Create.tpl
  tests/phpunit/CRM/Contract/Form/CreateFormTest.php
Labels: bug, status:needs work

#98 Implement payment instrument changes
  CRM/Contract/Change/Upgrade.php
  CRM/Contract/Configuration.php
  CRM/Contract/Form/Create.php
  CRM/Contract/Form/Modify.php
  CRM/Contract/RecurringContribution.php
  CRM/Contract/SepaLogic.php
  CRM/Contract/Upgrader.php
  contract.php
  js/contract_modify_tools.js
  templates/CRM/Contract/Form/Create.tpl
  templates/CRM/Contract/Page/Review.tpl
  tests/phpunit/CRM/Contract/Form/CreateFormTest.php
  tests/phpunit/CRM/Contract/Form/ModifyFormTest.php
Labels: bug, status:reviewed and tested
